server:
  port: 8002

spring:
  application:
    name: STUDENT-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: your_username
    password: your_password
    url: jdbc:mysql://localhost:3306/your-db
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

