server:
  port: 8002

spring:
  application:
    name: STUDENT-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    password: password
    url: jdbc:mysql://localhost:3306/your_db
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

